### ISSUE TITLE
Include form field description

### ISSUE THREAD

**Issue by mikemajara** [francisconeves97/react-google-forms-hooks#19]

**Comment by mikemajara** [comment]
It'd be nice to have the field description parsed too. I could give it a go as soon as I make some time.

**Comment by francisconeves97** [comment]
Hey @mikemajara! 

Great suggestion, if you have the time feel free to open a PR and I'll be happy to help and review it. 🙏 

Thanks a lot for the feedback, really glad that this project is helpful for other people :D
