### ISSUE TITLE
JSON.parse error due to a dangling ";" at the end of scriptHtml

### ISSUE THREAD

**Issue by DanielOrtel** [francisconeves97/react-google-forms-hooks#25]
I'm getting a `SyntaxError: Unexpected token ; in JSON at position 10828`, due to there being a dangling `;` at the end of the file with some larger google forms. I've investigated, and it turns out that [this line](https://github.com/francisconeves97/react-google-forms-hooks/blob/master/src/scripts/googleFormsToJson.ts#L68) misses the last `;`, though for what reason, I do not know. 

Confirmed, by manually removing the last element by `scriptHtml = scriptHtml.slice(0, -1);`, the `JSON.parse` is successful.

**Comment by DanielOrtel** [comment]
nevermind, I found the answer, did not know about this quirk of `replace`, but `.replace(<string expression>)` will only replace the first occurrence, you have to use a regex with a `g` flag to replace all occurrences: `scriptHtml = scriptHtml.replace(/;/g, '');`

**Comment by francisconeves97** [comment]
Hey @DanielOrtel! I can't reproduce that behavior with my example's form. Could you share your form so I can check it? The reason why we need to remove that `;` is because we want to parse the array that is stored within the `FB_PUBLIC_LOAD_DATA_` variable. To use JSON.parse() on that value, we need first to remove that `;`

It's not the cleanest thing I know 😛 but for every case I checked it has been working

Thank you for reporting this 🙏 but I think we need some more information on how to reproduce it

**Comment by DanielOrtel** [comment]
oh, hey, yeah, the problem arises with any json that contains a special character,[ like this form](https://docs.google.com/forms/d/e/1FAIpQLSfVAfrBzJ8PuvLmLofwmwH4zMsWimcLNxl7q5kGfgiyV-53Ig/viewform), though I'm honestly unsure what's causing it, since I tried to create some forms that contain special characters, and they didn't cause issues, but this one does, and it's guaranteed that it's because there's a dangling `;` at the end there

**Comment by francisconeves97** [comment]
Ohhh that makes lots of sense! Thank you for clarifying @DanielOrtel!

I think your suggestion of doing a `slice(0, -1)` should do the trick indeed. I am going to try it and deploy a fix

**Comment by francisconeves97** [comment]
https://github.com/all-contributors please add @DanielOrtel for bug

**Comment by francisconeves97** [comment]
@all-contributors please add @DanielOrtel for bug

**Comment by francisconeves97** [comment]
Hey @DanielOrtel! Released a fix for this on version `1.2.4`: https://github.com/francisconeves97/react-google-forms-hooks/releases/tag/1.2.4. 

Thank you again for the report

**Comment by DanielOrtel** [comment]
hey, thanks for the quick fix!
