### ISSUE TITLE
Any example to get the response of the form.

### ISSUE THREAD

**Issue by anandjaisy** [francisconeves97/react-google-forms-hooks#29]
Is there any example to read the response of the form

**Comment by francisconeves97** [comment]
Hey @anandjaisy! Could you give a little bit more detail please? I’m not sure if I got your question, I’m sorry!

**Comment by anandjaisy** [comment]
When you make the form as quiz, and others can response to it. Is there any way to get the response of that ?

**Comment by francisconeves97** [comment]
There is an example on how to use the library in the repo. Not sure if that helps? https://github.com/francisconeves97/react-google-forms-hooks/blob/100b8556a34c0ed7bc190b62fa59bd266f9c7de1/example/src/App.js#L91

I’m still a little bit unsure what you mean by response. Do you mean before submitting to google forms, if there is a way to get an object with the user’s answers?

**Comment by anandjaisy** [comment]
@francisconeves97 I need to access this url `https://forms.googleapis.com/v1beta/forms/{FORM-ID}/responses`

Is there any example of that

**Comment by francisconeves97** [comment]
Oh I see. Sorry this library doesn’t allow you to do that

**Comment by francisconeves97** [comment]
Closing as this is not an issue with the library
