### ISSUE TITLE
date fields are not recognized

### ISSUE THREAD

**Issue by dohomi** [francisconeves97/react-google-forms-hooks#3]
Hello

I just found your lib very interesting. By the first run I realized that date fields are not recognized. 

Cheers

**Comment by francisconeves97** [comment]
Hey @dohomi! Thank you for opening this issue.

Makes me really happy that you are using the lib and find it interesting.

The date field is not yet supported. I implemented this library to meet my needs so there are some inputs that were left out. I tried to disclaim this in the README.

> The list of supported inputs doesn't feature every input from Google Forms. Supported inputs: Short Answer, Long Answer, Checkbox, Radio, Dropdown, Linear, Radio Grid, Checkbox Grid

I will try to add support to the date field when I have the time. If you want to contribute with a PR feel free to do it as well, I am very happy to receive new contributors.

**Comment by dohomi** [comment]
Hi @francisconeves97 

I was using googleformrestyler.apixml.net which just went offline yesterday so I am quite happy that I found your package. I have a suggestion though: separate the server side functions and client side functions into 2 repos, then it would be easier to maintain. 

I copied just for digging into it your googleFormsToJson some code and thats pretty much the Date object:
```ts

parseFieldType ==>
if (fieldId === 9) {
    return 'DATE'
  } 

 export type GoogleFormWithDate = Omit<GoogleForm, 'fields'> & {
  fields: FieldWithDate[]
}

export interface DateField {
  id: string
  label: string
  required: boolean
  type: 'DATE'
}

export type FieldWithDate = Field | DateField

parseField ==>
  case 'DATE': {
      const fieldInfo = rawField[4][0]
      field.id = toString(fieldInfo[0])
      field.required = toBool(rawField[4][0][2])
      break
    }
```

If I have more time I'd try to contribute in a smoother way

**Comment by francisconeves97** [comment]
Thank you for your suggestions @dohomi! 

I understand your points, it's true that this library comes with some dependencies attached. I may look into a way of splitting the lib so not all the dependencies are needed, splitting by client and server sounds like a good idea. However getting the time to do so is harder 😛 

I started developing a branch to support this and may end it this weekend or the next one, in case you are interested: https://github.com/francisconeves97/react-google-forms-hooks/tree/feat/add-date-field

**Comment by dohomi** [comment]
Hi @francisconeves97 
as the server side code does not actually has anything to do with react, would you be keen to create a separate repo for it? Instead using axios I would recommend using node-fetch for the call which will significantly drop the bundle size.

**Comment by dohomi** [comment]
Ah by the way I just saw you are using microbundle as well (I do too)

I would just create a packages folder and then re-initialize both endpoints with moving the src folder into the package named folder. With that way you will be able to split both packages with both of them having its own package.json setup

**Comment by dohomi** [comment]
solved :-)
